version: '3.8'

services:
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
    - ./config:/mosquitto/config
    - ./config:/mosquitto/data
    - ./config:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
  redis:
    image: redis/redis-stack
    container_name: redis
    restart: always
    volumes:
    - redis_volume_data:/data
    ports:
      - 6379:6379
      - 8001:8001
volumes:
  config:
  data:
  log:
  redis_volume_data: